baseURL = "http://example.org/"
languageCode = "en-us"
title = "La Jarra"

DefaultContentLanguage = "es"
[languages]
  [languages.es]
    #title = "Espanol"
    languageName = "Spanish"
    weight = 1
  [languages.en]
    #title = "English"
    languageName = "English"
    weight = 2


[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"
  
  
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/article/"
    weight = 2

[params]
	postsInFooter = 2
    socialMediaLinks = [      
      { link = "https://www.linkedin.com/in/geiber-ugalde-7a0a4b196", icon = "fab fa-linkedin fa-2x" },
	  { link = "https://twitter.com/geiber", icon = "fab fa-twitter" },
    ]
	
    copyrightBy = "by geiber"
    copyrightUseCurrentYear = false 
    copyrightYearOverride = "2020"
    copyrightUrl = "https://geiber.dev"


	logoImg = "img/Jarra6.png"


	

